### ISSUE TITLE
编辑闹钟无效bug

### ISSUE THREAD

**Issue by LyongY** [SunriseOYR/Alarm_Clock_UserNotifications#1]
你好，刚在使用你这个Demo时发现一个bug，比如我设置了一个6点15的闹钟（没有设置重复） 到了6点15 闹钟响完之后，我再编辑这个闹钟 设置时间为6点20，到了6点20，闹钟不会响。

**Comment by SunriseOYR** [comment]
你好，非常感谢你发现了这个bug，今天才看到这个问题，已经做了处理，原因是编辑的时候，时间被重置到2001年了，所以闹钟不会响
