### ISSUE TITLE
如何到时间点：持续通知直到用户进入app才能关闭它

### ISSUE THREAD

**Issue by Jacky-LinPeng** [SunriseOYR/Alarm_Clock_UserNotifications#3]
你这个到点只会本地通知一次，如何实现到点进行不间断的通知 ，有没有可以实现的方案？
Alarmy这个app实现了持续通知的功能，它似乎是规避了 最大64个local notify的数量限制

**Comment by SunriseOYR** [comment]
一个通知 只会响应一次， 你可以为一个时间添加多个通知，就会响应多次， 添加的时候，你可以判断次数，大于64 就移除并记录最旧的通知，等有通知响应了，再添加

**Comment by Jacky-LinPeng** [comment]
> 一个通知 只会响应一次， 你可以为一个时间添加多个通知，就会响应多次， 添加的时候，你可以判断次数，大于64 就移除并记录最旧的通知，等有通知响应了，再添加

我的需求是 到达 8:00 am 的时候 一直弹通知（用户没进入app手动关掉就无限的提醒）通知的间隔5s,    UNCalendarNotificationTrigger(只能限制64个，app kill之前我就必须要添加进去，但是最多是弹64就没了 无法做到无限提醒)  和  UNTimeIntervalNotificationTrigger（repeat 间隔必须大于60s） 似乎无法满足 我有点没思路 不知道大神有什么方案demo没

**Comment by SunriseOYR** [comment]
这个苹果限制了，是无法达到你这种需求的， 你可以去测试 一下应用市场上的app， 应该是都不行的

**Comment by Jacky-LinPeng** [comment]
你去App Store搜索一下 Alarmy 这个App  
它居然实现了 想不通他是如何实现的...

**Comment by lifeMiik** [comment]
老哥，有实现方案吗，只能响应三十秒，如果不是息屏的情况下，更短，好像并不能做到系统的闹钟那样
